export const CSS_VARIABLE_KEYS = [
	'--ui-bg',
	'--ui-surface',
	'--ui-surface-2',
	'--ui-surface-strong',
	'--ui-border',
	'--ui-border-strong',
	'--ui-border-subtle',
	'--ui-text',
	'--ui-muted',
	'--ui-accent',
	'--ui-accent-strong',
	'--ui-accent-border',
	'--ui-success',
	'--ui-success-bg',
	'--ui-success-border',
	'--ui-success-text',
	'--ui-warning',
	'--ui-warning-bg',
	'--ui-warning-border',
	'--ui-warning-text',
	'--ui-danger',
	'--ui-danger-strong',
	'--ui-danger-bg',
	'--ui-danger-border',
	'--ui-danger-text',
	'--ui-code-bg',
	'--ui-code-text',
	'--ui-hover',
	'--ui-empty-bg',
	'--ui-overlay',
	'--ui-glow',
	'--ui-glow-muted',
	'--ui-glow-dim',
	'--ui-selection-text',
	'color-scheme'
] as const;

export type CssVariableKey = (typeof CSS_VARIABLE_KEYS)[number];
