use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

fn extract_placeholders(s: &str) -> BTreeSet<String> {
    let mut result = BTreeSet::new();
    let mut rest = s;
    while let Some(start) = rest.find('{') {
        if let Some(end) = rest[start..].find('}') {
            let name = &rest[start + 1..start + end];
            if !name.is_empty() {
                result.insert(name.to_string());
            }
            rest = &rest[start + end + 1..];
        } else {
            break;
        }
    }
    result
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let i18n_dir = Path::new(&manifest_dir).join("i18n");

    println!("cargo::rerun-if-changed=i18n/en.toml");
    println!("cargo::rerun-if-changed=i18n/ru.toml");

    let en_raw = fs::read_to_string(i18n_dir.join("en.toml")).unwrap();
    let ru_raw = fs::read_to_string(i18n_dir.join("ru.toml")).unwrap();

    let en: toml::Value = toml::from_str(&en_raw).unwrap();
    let ru: toml::Value = toml::from_str(&ru_raw).unwrap();

    let en_t = en.as_table().unwrap();
    let ru_t = ru.as_table().unwrap();

    let mut out = String::new();
    out.push_str("// auto-generated by build.rs\n// source: i18n/en.toml, i18n/ru.toml\n\n");

    for (key, ev) in en_t {
        let e = ev.as_str().unwrap();
        let r = ru_t.get(key).unwrap().as_str().unwrap();
        let upper = key.to_uppercase();
        out.push_str(&format!("const EN_{upper}: &str = {e:?};\n"));
        out.push_str(&format!("const RU_{upper}: &str = {r:?};\n"));
    }

    for (key, ev) in en_t {
        let e = ev.as_str().unwrap();
        let r = ru_t.get(key).unwrap().as_str().unwrap();

        let mut placeholders = extract_placeholders(e);
        placeholders.extend(extract_placeholders(r));

        let upper = key.to_uppercase();
        if placeholders.is_empty() {
            out.push_str(&format!(
                "pub fn {key}(lang: usize) -> &'static str {{\n    if lang == 0 {{ EN_{upper} }} else {{ RU_{upper} }}\n}}\n\n"
            ));
        } else {
            let params: Vec<String> = placeholders.iter().map(|p| format!("{p}: &str")).collect();
            out.push_str(&format!(
                "pub fn {key}(lang: usize, {}) -> String {{\n    let s = if lang == 0 {{ EN_{upper} }} else {{ RU_{upper} }};\n",
                params.join(", ")
            ));
            let count = placeholders.len();
            for (i, p) in placeholders.iter().enumerate() {
                if i == count - 1 {
                    out.push_str(&format!("    s.replace(\"{{{p}}}\", {p})\n"));
                } else {
                    out.push_str(&format!("    let s = s.replace(\"{{{p}}}\", {p});\n"));
                }
            }
            out.push_str("}\n\n");
        }
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("i18n_gen.rs"), out).unwrap();
}
